### ISSUE TITLE
图像预处理阶段有个问题

### ISSUE THREAD

**Issue by liangzz1991** [haqishen/SIIM-ISIC-Melanoma-Classification-1st-Place-Solution#2]
![image](https://user-images.githubusercontent.com/12033811/96853862-6e652a00-148d-11eb-8341-18166ae5b0d6.png)
这里，opencv不是读入BGR 格式的array嘛，怎么cvtcolor用rgb2bgr呢？同时albumentations的transform需要读入的也是rgb格式的arrary啊，

**Comment by GiangHLe** [comment]
I think just a little mistake from them, but the result should be the same, OpenCV read images in BGR order, so use `cv2.COLOR_RGB2BGR` just swap B and R, so they still correct with `albumentations` format.

**Comment by haqishen** [comment]
Thanks @lhgiang149 for the answer and yes that's correct ;)

I fixed it to aviod further misunderstanding.

https://github.com/haqishen/SIIM-ISIC-Melanoma-Classification-1st-Place-Solution/commit/b2e7d31a64fa42ab3abd7cbd0046e733d213702a
