### ISSUE TITLE
Question about meta data

### ISSUE THREAD

**Issue by GiangHLe** [haqishen/SIIM-ISIC-Melanoma-Classification-1st-Place-Solution#3]
Hi,
I saw your idea that concat the result from image through CNNs model and the vector from meta data (data frame). Is it your idea, or it depend on a paper or some tutorials ? 
If it depend on something, please give me the link to it. 
Thank you.

**Comment by haqishen** [comment]
It depends on some previous kaggle competitions.
I saw that on more than 1 previous kaggle competitions, people used that idea to combine meta data with images.

**Comment by GiangHLe** [comment]
okay, I see, I tend to pre-produce your work, thank you for your answer

**Comment by GiangHLe** [comment]
Ah sorry, if possible, can you show me how can you deal with metadata. I mean how you pre-process the Dataframe before put it in linear model

**Comment by GiangHLe** [comment]
ah okay, I found it in the code, sorry for disturbing you
